name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  Release:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        nodejs: [16]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Authenticate with private NPM package
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Install and link
      run: yarn install --frozen-lockfile

    - name: git config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      env:
        GITHUB_TOKEN: ${{ secrets.OVERRIDE_GITHUB_TOKEN }}

    - name: Test Production Bundle & Release
      run: npx release-it minor --ci -VV
      env:
        GITHUB_TOKEN: ${{ secrets.OVERRIDE_GITHUB_TOKEN }}